export const FETCH_NEWSSTOCK_LIST = 'FETCH_NEWSSTOCK_LIST';
export const FETCH_NEWSSTOCK_LIST_SUCCESS = 'FETCH_NEWSSTOCK_LIST_SUCCESS';
export const FETCH_NEWSSTOCK_LIST_ERROR = 'FETCH_NEWSSTOCK_LIST_ERROR';

export const INCREASE_PAGE_NUMBER = 'INCREASE_PAGE_NUMBER';
